'C/C++':
  - '**/*.c'
  - '**/*.cpp'
  - '**/*.h'
  - '**/*.hpp'

'TypeScript':
  - '**/*.ts'
  - '**/*.tsx'

'Python':
  - '**/*.py'

'Driver':
  - 'Drivers/**/*'

'CI/CD':
  - '.github/**/*'

'documentation':
  - 'docs/**/*'
  - '**/*.md'

'Build System':
  - '**/CMakeLists.txt'
  - '**/*.cmake'