'C/C++':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'

'TypeScript':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.ts'
      - '**/*.tsx'

'Python':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.py'

'Arduino':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.ino'
      - '**/*.pde'

'Driver':
  - changed-files:
    - any-glob-to-any-file: 
      - 'Drivers/**/*'

'CI/CD':
  - changed-files:
    - any-glob-to-any-file: 
      - '.github/**/*'

'documentation':
  - changed-files:
    - any-glob-to-any-file: 
      - 'docs/**/*'
      - '**/*.md'

'Build System':
  - changed-files:
    - any-glob-to-any-file: 
      - '**/CMakeLists.txt'
      - '**/*.cmake'