name: Central Ceedling Unit Tests
on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetches common repo

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Ceedling & Dependencies
        run: |
          gem install ceedling
          sudo apt-get update && sudo apt-get install -y gcovr gcc

      - name: Run Unit Tests
        run: |
          mkdir -p test/support
          ceedling test:all

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/artifacts/test/junit_tests_report.xml